defaults:
  - network: dqn_nn
  - _self_

description: dqn
num_iterations: 1_000
eval_period: 50
batch_size: 32
td_gamma: 0.99
target_update_period: 5
target_update_tau: 0.001
num_intervals_discretized: 20
data_collector_frames_per_batch: 50
replay_buffer_capacity: 20_000
train_iterations_per_frame: 32 
