hydra:
  run:
    dir: ${output_path}/${name}

defaults:
  - mode: local
  - algorithm: dqn
  - _self_

name: LL_DQN_02
output_path: outputs
model_path: models
data:
  energy_dataset_path: data/Final_Energy_dataset.csv
  price_dataset_path: data/price.csv
use_forecast: true
env:
  customer: [1,2,3,4,5,6,7,8,9,10]
  timeslots_per_day: 48
  forecast_horizon: 48
  init_charge: 0.0
device: cpu
