hydra:
  run:
    dir: ${output_path}/${name}

defaults:
  - mode: local
  - networks: nn
  - _self_

name: ll_22
output_path: outputs
dataset_path: data/Final_Energy_dataset.csv
env:
  customer: [1,2,3]
  timeslots_per_day: 48
  forecast_horizon: 6
  capacity: 13.5
  power_battery: 4.6
  init_charge: 0.0
ddpg:
  data_collector_frames_per_batch: 50
  data_collector_init_frames: 50
  replay_buffer_capacity: 20_000
  num_iterations: 100
  train_iterations_per_frame: 32
  target_update_period: 1
  target_update_tau: 0.001
  td_gamma: 0.99
  batch_size: 64
  eval_period: 250
device: cpu
