hydra:
  run:
    dir: ${output_path}/${name}

defaults:
  - mode: local
  - algorithm: ddpg
  - _self_

name: LL_DDPG_FC_10
output_path: outputs
model_path: models
data:
  energy_dataset_path: data/1_processed/energy.csv
  price_dataset_path: data/1_processed/price.csv
use_forecast: false
env:
  customer: [1,2,5]
  forecast_horizon: 10
  init_charge: 0.0
seed: 42
device: cpu
