datasets:
  path: data/train.csv

env_params:
  init_charge: 0.0
  timeslots_per_day: 48
  days: 365
  capacity: 13.5
  power_battery: 4.6
  ecoPriority: 0
  logging: False
  feed_in_price: 0.076

params:
  num_iterations: 40000
  initial_collect_steps: 1000
  collect_steps_per_iteration: 1
  replay_buffer_capacity: 100000 
  ou_stddev: 0.2
  ou_damping: 0.15
  target_update_tau: 0.05
  target_update_period: 5
  batch_size: 64
  actor_learning_rate: 1e-4
  critic_learning_rate: 1e-3
  gamma: 0.99
  reward_scale_factor: 1.0