hydra:
  run:
    dir: ${output_path}/${name}

defaults:
  - mode: local
  - networks: nn
  - _self_

name: fl_v3
output_path: outputs
dataset_path: ../data/Final_Energy_dataset.csv
env:
  customer: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  timeslots_per_day: 48
  forecast_horizon: 48
  capacity: 13.5
  power_battery: 4.6
  init_charge: 0.0
ddpg:
  early_stopping_patience: 5
  data_collector_frames_per_batch: 50 # One full day
  data_collector_init_frames: 50
  replay_buffer_capacity: 20_000
  num_iterations: 3000
  train_iterations_per_frame: 32 
  target_update_period: 5 #1
  target_update_tau: 0.001
  td_gamma: 0.99
  batch_size: 64 # Larger batch size for more stable gradients
  eval_period: 3000
federated:
  num_fed_rounds: 5
  num_local_rounds: 2000
personalized_fed:
   num_shared_layers: 1
device: cpu
