hydra:
  run:
    dir: ${output_path}/${name}

defaults:
  - mode: local
  - algorithm: dqn
  - _self_

name: LL_DQN_01
output_path: outputs
model_path: models/${name}
data:
  energy_dataset_path: data/Final_Energy_dataset.csv
  price_dataset_path: data/price.csv
  
env:
  customer: [1]
  timeslots_per_day: 48
  forecast_horizon: 48
  init_charge: 0.0
device: cpu
